### PR TITLE
Fix Linux clang/gcc compile error - include optional

### PR DESCRIPTION
**Pull request by UffeJakobsen**
```
In file included from /tmp/Plugin/FileManager.cpp:1: /tmp/Plugin/FileManager.hpp:33:17: error: no template named 'optional' in namespace 'std'
   33 |     static std::optional<wxString> ReadContent(const wxString& filepath, const wxMBConv& conv = wxConvUTF8);
      |            ~~~~~^
/tmp/Plugin/FileManager.hpp:34:17: error: no template named 'optional' in namespace 'std'
   34 |     static std::optional<wxString> ReadSettingsFileContent(const wxString& name);
      |            ~~~~~^
2 errors generated.
```

### CODE REVIEW

**Comment by Jarod42** [comment]
Seems not the only issue:

> /home/runner/work/codelite/codelite/Plugin/FileManager.cpp: In static member function ‘static bool FileManager::Create(const wxString&)’:
> /home/runner/work/codelite/codelite/Plugin/FileManager.cpp:65:13: error: ‘clSFTPManager’ has not been declared
>   65 |         if (clSFTPManager::Get().IsFileExists(fullpath, workspace->GetSshAccount())) {

**Comment by UffeJakobsen** [comment]
> Seems not the only issue:
> 
> > /home/runner/work/codelite/codelite/Plugin/FileManager.cpp: In static member function ‘static bool FileManager::Create(const wxString&)’:
> > /home/runner/work/codelite/codelite/Plugin/FileManager.cpp:65:13: error: ‘clSFTPManager’ has not been declared
> > 65 |         if (clSFTPManager::Get().IsFileExists(fullpath, workspace->GetSshAccount())) {

Strange - I do not see that error on local builds using GCC-15.2.1 or clang-20.1.8

**Comment by eranif** [comment]
So the issue is when building without SFTP support.

```bash
cmake .. -DCMAKE_BUILD_TYPE=Release -DENABLE_SFTP=0
```

**Comment by UffeJakobsen** [comment]
added by other commit
