### ISSUE TITLE
PLUGIN: cannot build with wxWidgets < 3.1.0

### ISSUE THREAD

**Issue by carlo-bramini** [eranif/codelite#3022]
I'm getting this error when building:

```
[ 42%] Building CXX object Plugin/CMakeFiles/plugin.dir/clGenericNotebook.cpp.o
/home/carlo/codelite/Plugin/clGenericNotebook.cpp: In function ‘wxRect {anonymous}::GetFileListButtonRect(wxWindow*, size_t, wxDC&)’:
/home/carlo/codelite/Plugin/clGenericNotebook.cpp:69:21: error: ‘class wxWindow’ has no member named ‘FromDIP’
   69 |     rr.Inflate(win->FromDIP(5));
      |                     ^~~~~~~
make[2]: *** [Plugin/CMakeFiles/plugin.dir/build.make:2797: Plugin/CMakeFiles/plugin.dir/clGenericNotebook.cpp.o] Error 1
```

Perhaps, this needs to be fixed with an `#if wxVERSION_NUMBER >= 3100 ... #endif`, like it has been done into other parts of the source code.

**Comment by eranif** [comment]
We no longer support wx3.0
You should have wx3.1.6 or later
