### ISSUE TITLE
[Bug]: Redefinition of 'struct hash<wxString>'

### ISSUE THREAD

**Issue by genpfault** [eranif/codelite#3119]
### What happened?

Trying to compile 16.7.0 (cadf8b9ae2) on Debian Bullseye and it's not liking the `std::hash` usage in the DAP code.

CMake configure output:

```none
-- The C compiler identification is GNU 10.2.1
-- The CXX compiler identification is GNU 10.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found SQLite3: /usr/include (found version "3.34.1") 
-- BUILD_DIRECTORY is set to /home/genpfault/Workspace/codelite/build-release
-- OS name Linux
-- wx-config used is: /usr/bin/wx-config
-- wxWidgets version is: 3.0.5
-- gtk version is: 3
-- LIBSSH_LIB is set to /usr/lib/x86_64-linux-gnu/libssh.so
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2") 
-- Checking for module 'gtk+-3.0'
--   Found gtk+-3.0, version 3.24.24
-- Checking for module 'gdk-pixbuf-2.0'
--   Found gdk-pixbuf-2.0, version 2.42.2
-- Checking for one of the modules 'glib-2.0'
-- Found GLib2: glib-2.0 /usr/include/glib-2.0;/usr/lib/x86_64-linux-gnu/glib-2.0/include
-- Looking for include file glib/gregex.h
-- Looking for include file glib/gregex.h - not found
-- Checking for module 'pango'
--   Found pango, version 1.46.2
-- Checking for module 'atk'
--   Found atk, version 2.36.0
-- Found GTK3: /usr/lib/x86_64-linux-gnu/libgtk-3.so  
-- Found wxWidgets: -L/usr/lib/x86_64-linux-gnu;-pthread;;;-lwx_gtk3u_adv-3.0;-lwx_gtk3u_aui-3.0;-lwx_baseu-3.0;-lwx_gtk3u_core-3.0;-lwx_gtk3u_html-3.0;-lwx_gtk3u_propgrid-3.0;-lwx_baseu_xml-3.0;-lwx_gtk3u_xrc-3.0;-lwx_baseu_net-3.0;-lwx_gtk3u_stc-3.0;-lwx_gtk3u_ribbon-3.0;-lwx_gtk3u_richtext-3.0 (found version "3.0.5") 
-- PLUGINS_DIR is set to /usr/lib/x86_64-linux-gnu/codelite
-- Using Native Notebook class
-- Building in Release mode
-- CMAKE_INSTALL_DO_STRIP is TRUE
-- Executables will be written into /home/genpfault/Workspace/codelite/build-release/bin
-- Shared Objects will be written into /home/genpfault/Workspace/codelite/build-release/lib
-- Adding -DNDEBUG to definitions
-- CPACK_SYSTEM_NAME debian-bullseye-x86_64
-- OS_CODENAME is set to bullseye
-- ARCH 64
-- ARCH_NAME x86_64
-- USE_SFTP is set to 1
-- Flex support is disabled
-- Looking for setenv
-- Looking for setenv - found
-- Looking for putenv
-- Looking for putenv - found
-- Looking for direct.h
-- Looking for direct.h - not found
-- Looking for dirent.h
-- Looking for dirent.h - found
-- Looking for fcntl.h
-- Looking for fcntl.h - found
-- Looking for io.h
-- Looking for io.h - not found
-- Looking for stat.h
-- Looking for stat.h - not found
-- Looking for types.h
-- Looking for types.h - not found
-- Looking for unistd.h
-- Looking for unistd.h - found
-- Looking for sys/dir.h
-- Looking for sys/dir.h - found
-- Looking for sys/stat.h
-- Looking for sys/stat.h - found
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for sys/wait.h
-- Looking for sys/wait.h - found
-- Looking for stdbool.h
-- Looking for stdbool.h - found
-- Looking for regex.h
-- Looking for regex.h - found
-- Looking for regcomp
-- Looking for regcomp - found
-- Performing Test Iconv_IS_BUILT_IN
-- Performing Test Iconv_IS_BUILT_IN - Success
-- Looking for fnmatch.h
-- Looking for fnmatch.h - found
-- Looking for mkstemp
-- Looking for mkstemp - found
-- Found libhunspell: /usr/lib/x86_64-linux-gnu/libhunspell.so, /usr/include/hunspell
-- Found wxWidgets: -L/usr/lib/x86_64-linux-gnu;-pthread;;;-lwx_gtk3u_adv-3.0;-lwx_gtk3u_aui-3.0;-lwx_baseu-3.0;-lwx_gtk3u_core-3.0;-lwx_baseu_xml-3.0;-lwx_gtk3u_xrc-3.0;-lwx_baseu_net-3.0;-lwx_gtk3u_stc-3.0;-lwx_gtk3u_richtext-3.0 (found version "3.0.5") 
-- CL_SRC_ROOT is set to /home/genpfault/Workspace/codelite
-- Adding Valgrind Plugin
-- Building wxCrafter as codelite plugin 
-- Generating makefile for wxCrafter
-- wxlibsdir is: /usr/lib/x86_64-linux-gnu
-I/usr/lib/x86_64-linux-gnu/wx/include/gtk3-unicode-3.0 -I/usr/include/wx-3.0 -D_FILE_OFFSET_BITS=64 -DWXUSINGDLL -D__WXGTK__ -pthread
-- Including plugin.cmake module
-- CMAKE_SOURCE_DIR is set to /home/genpfault/Workspace/codelite
-- Configuring done
-- Generating done
-- Build files have been written to: /home/genpfault/Workspace/codelite/build-release
```

### Version

Self compiled

### Operating system

Linux

### Steps to reproduce

```text
git checkout 16.7.0
rm -rf build-release
mkdir build-release
cd build-release
cmake -G "Ninja" -DCMAKE_BUILD_TYPE=Release .. -DCOPY_WX_LIBS=1
ninja
```

### Relevant log output

```shell
[289/1959] Building CXX object DebugAdapterClient/CMakeFiles/DebugAdapterClient.dir/DAPBreakpointsView.cpp.o
FAILED: DebugAdapterClient/CMakeFiles/DebugAdapterClient.dir/DAPBreakpointsView.cpp.o 
/usr/bin/c++ -DDebugAdapterClient_EXPORTS -DGTK_USE_NATIVEBOOK=1 -DINSTALL_DIR=\"/usr/share/codelite\" -DNDEBUG -DPLUGINS_DIR=\"/usr/lib/x86_64-linux-gnu/codelite\" -DUSE_SFTP=1 -DWXUSINGDLL -DWXUSINGDLL_CL -DWXUSINGDLL_DAP -DWXUSINGDLL_SDK -DWXUSINGDLL_WXSQLITE3 -DYY_NEVER_INTERACTIVE=1 -D_FILE_OFFSET_BITS=64 -D__WXGTK__ -DwxUSE_GUI=1 -I/usr/include/gtk-3.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/pango-1.0 -I/usr/include/cairo -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/atk-1.0 -I../Plugin -I../sdk/wxsqlite3/include -I../CodeLite -I../PCH -I../Interfaces -I../wxdap -isystem /usr/lib/x86_64-linux-gnu/wx/include/gtk3-unicode-3.0 -isystem /usr/include/wx-3.0 -Wno-deprecated-declarations -isystem /usr/include/harfbuzz -std=c++11 -g -O2 -ffile-prefix-map=/home/genpfault/Workspace/codelite/build-release=. -fstack-protector-strong -Wformat -Werror=format-security -O2 -pthread -fPIC   -Wdate-time -D_FORTIFY_SOURCE=2 -std=c++11 -MD -MT DebugAdapterClient/CMakeFiles/DebugAdapterClient.dir/DAPBreakpointsView.cpp.o -MF DebugAdapterClient/CMakeFiles/DebugAdapterClient.dir/DAPBreakpointsView.cpp.o.d -o DebugAdapterClient/CMakeFiles/DebugAdapterClient.dir/DAPBreakpointsView.cpp.o -c ../DebugAdapterClient/DAPBreakpointsView.cpp
In file included from ../CodeLite/macros.h:29,
                 from ../CodeLite/JSON.h:42,
                 from ../CodeLite/LSP/JSONObject.h:4,
                 from ../CodeLite/LSP/CompletionItem.h:4,
                 from ../CodeLite/cl_command_event.h:29,
                 from ../Plugin/clThemedSplitterWindow.h:4,
                 from ../DebugAdapterClient/UI.h:18,
                 from ../DebugAdapterClient/DAPBreakpointsView.h:5,
                 from ../DebugAdapterClient/DAPBreakpointsView.cpp:1:
../CodeLite/wxStringHash.h:15:12: error: redefinition of ‘struct std::hash<wxString>’
   15 |     struct hash<wxString>
      |            ^~~~~~~~~~~~~~
In file included from ../DebugAdapterClient/SessionBreakpoints.hpp:4,
                 from ../DebugAdapterClient/DAPBreakpointsView.h:4,
                 from ../DebugAdapterClient/DAPBreakpointsView.cpp:1:
../wxdap/dap/dap.hpp:18:8: note: previous definition of ‘struct std::hash<wxString>’
   18 | struct hash<wxString> {
      |        ^~~~~~~~~~~~~~
```

**Comment by genpfault** [comment]
Compiled without errors against a self-built wxWidgets v3.2.1 so the [version check in CMakeLists.txt](https://github.com/eranif/codelite/blob/16.7.0/CMakeLists.txt#L156-L160) probably just needs bumping up.

**Comment by genpfault** [comment]
Looks like the earliest wxWidgets release it'll build with is [v3.1.6](https://github.com/wxWidgets/wxWidgets/releases/tag/v3.1.6).

**Comment by genpfault** [comment]
> the [version check in CMakeLists.txt](https://github.com/eranif/codelite/blob/16.7.0/CMakeLists.txt#L156-L160) probably just needs bumping up.

For example:

```none
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 5e66101c1..304b3c004 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -150,12 +150,9 @@ if (UNIX OR MINGW)
         # cmake find_package() will try env var WX_CONFIG as wx-config tool path before checking its builtin hardcoded naming conbinations for wx-config tool
         set( ENV{WX_CONFIG} ${WX_TOOL} )
         execute_process(COMMAND sh ${WX_TOOL} --version OUTPUT_VARIABLE WX_VERSION OUTPUT_STRIP_TRAILING_WHITESPACE)
-        string(SUBSTRING "${WX_VERSION}" "0" "1" wxMAJOR_VERSION)
-        string(SUBSTRING "${WX_VERSION}" "2" "1" wxMINOR_VERSION)
-        string(SUBSTRING "${WX_VERSION}" "4" "1" wxRELEASE_NUMBER)
-        if ( wxMAJOR_VERSION LESS 3 )
+        if ( "${WX_VERSION}" VERSION_LESS "3.1.6" )
         message(FATAL_ERROR
-"\nI'm afraid your wxWidgets version is too old.\nBuilding CodeLite requires at least wxWidgets-3.0.0"
+"\nI'm afraid your wxWidgets version is too old.\nBuilding CodeLite requires at least wxWidgets-3.1.6"
              )
         endif()
         if (MINGW)
```
