### ISSUE TITLE
Can't compile with gcc 4.9

### ISSUE THREAD

**Issue by underdoeg** [eranif/codelite#463]
I was unable to compile codelite with gcc 4.9 on arch Linux 64bits. Tried with latest release and git version. Gcc 4.8 compiles ok.

The problem were several linker errors:

```
/home/phwhitfield/softwareSources/codelite-5.4/build-release/lib/libplugin.so: undefined reference to `wxCommandEvent::Clone() const'
collect2: error: ld returned 1 exit status
```

Arch bug report
https://aur.archlinux.org/packages/codelite/

Possible workaround is to disable -O3
https://aur.archlinux.org/packages/dolphin-emu-git/
