### ISSUE TITLE
wxWidgets related compile error

### ISSUE THREAD

**Issue by uffejakobsen** [eranif/codelite#2774]
Hi,

Latest master gives a wxWidgets related compile error due to code incompatibility with stable wxWidgets 3.0.x (see below)

It seems that there have been quite a few of these errors lately - on the positive side it is a good indication that you are quite active on the development side :-) :+1: 

But would it make sense to create a new github action that builds with the stable wxWidgets 3.0.x parallel to the current builds with unstable wxWidgets 3.1.x ?

```
/tmp/uj.dir/codelite.git/Plugin/cc_box_tip_window.cpp: In member function ‘void CCBoxTipWindow::DoInitialize(size_t, bool)’:
/tmp/uj.dir/codelite.git/Plugin/cc_box_tip_window.cpp:153:17: error: invalid conversion from ‘CCBoxTipWindow*’ to ‘unsigned int’ [-fpermissive]
  153 |     wxDisplay d(this);
      |                 ^~~~
      |                 |
      |                 CCBoxTipWindow*
In file included from /tmp/uj.dir/codelite.git/Plugin/cc_box_tip_window.cpp:48:
/usr/include/wx-3.0/wx/display.h:47:24: note:   initializing argument 1 of ‘wxDisplay::wxDisplay(unsigned int)’
   47 |     wxDisplay(unsigned n = 0);
      |               ~~~~~~~~~^~~~~
/tmp/uj.dir/codelite.git/Plugin/cc_box_tip_window.cpp: In member function ‘void CCBoxTipWindow::PositionRelativeTo(wxWindow*, wxPoint, IEditor*)’:
/tmp/uj.dir/codelite.git/Plugin/cc_box_tip_window.cpp:193:36: error: invalid conversion from ‘CCBoxTipWindow*’ to ‘unsigned int’ [-fpermissive]
  193 |     wxRect displaySize = wxDisplay(this).GetClientArea();
      |                                    ^~~~
      |                                    |
      |                                    CCBoxTipWindow*
In file included from /tmp/uj.dir/codelite.git/Plugin/cc_box_tip_window.cpp:48:
/usr/include/wx-3.0/wx/display.h:47:24: note:   initializing argument 1 of ‘wxDisplay::wxDisplay(unsigned int)’
   47 |     wxDisplay(unsigned n = 0);
      |               ~~~~~~~~~^~~~~
```

**Comment by eranif** [comment]
should be fixed with recent master

**Comment by uffejakobsen** [comment]
```

```


> should be fixed with recent master

Unfortunately - no -you only fixed the first error - that means that I'm unable to publish the new 15.0.5 - since it does not build with the stable wx 3.0.x (same problem with 15.0.4)

```
/tmp/uj.dir/codelite.git/Plugin/cc_box_tip_window.cpp: In member function ‘void CCBoxTipWindow::PositionRelativeTo(wxWindow*, wxPoint, IEditor*)’:
/tmp/uj.dir/codelite.git/Plugin/cc_box_tip_window.cpp:198:36: error: invalid conversion from ‘CCBoxTipWindow*’ to ‘unsigned int’ [-fpermissive]
  198 |     wxRect displaySize = wxDisplay(this).GetClientArea();
      |                                    ^~~~
      |                                    |
      |                                    CCBoxTipWindow*
In file included from /tmp/uj.dir/codelite.git/Plugin/cc_box_tip_window.cpp:48:
/usr/include/wx-3.0/wx/display.h:47:24: note:   initializing argument 1 of ‘wxDisplay::wxDisplay(unsigned int)’
   47 |     wxDisplay(unsigned n = 0);
      |               ~~~~~~~~~^~~~~
```

**Comment by eranif** [comment]
I can make a tag `15.0.5.1` for this purpose, will this help?

**Comment by uffejakobsen** [comment]
Yes that would be fantastic :-)

thanks for your effort :+1:

**Comment by eranif** [comment]
Tag `15.0.5-1` pushed
