### ISSUE TITLE
Arguments in wxWidgets projects' templates tend not to work on OS X

### ISSUE THREAD

**Issue by assp1r1n3** [eranif/codelite#599]
When creating a project from template of any wxWidgets app, wxWidgets's files are not included and this results in build error. If you open the C++ compiler arguments, by default you will see there:

``` bash
-O2;-Wall;$(shell wx-config --cxxflags --unicode=yes --debug=yes)
```

This doesn't work on OS X (at least 10.10) as there is no shell command:

``` bash
assp1r1n3$ $(shell wx-config --cxxflags --unicode=yes --debug=yes)
-bash: shell: command not found
```

A number of solutions have been tried, but without luck, because of newline characters in `wx-config`'s output.
Solutions include:

``` bash
$(bash wx-config --cxxflags --unicode=yes --debug=yes)
```

``` bash
$(wx-config --cxxflags --unicode=yes --debug=yes)
```

**Comment by HonzaMac** [comment]
I have same issue. 
For me works just simple calling from cli "make" and it compiles correctly.
But "Build" from codelite does not work.

```
/bin/sh -c '/usr/bin/make -j4 -e -f  Makefile'
----------Building project:[ calc - Debug ]----------
make[1]: wx-config: Command not found
make[1]: wx-config: Command not found
wxcrafter_bitmaps.cpp:16:20: error: token is not a valid binary operator in a preprocessor subexpression
#if wxCHECK_VERSION(2,8,5) && wxABI_VERSION >= 20805
    ~~~~~~~~~~~~~~~^
1 error generated.
make[1]: wx-config: Command not found
make[1]: wx-config: Command not found
/usr/bin/g++   -c  "/Users/honza/projects/calc/main.cpp" -g -O0 -Wall   -o ./Debug/main.cpp.o -I/usr/local/bin  -I. -I.
/usr/bin/g++   -c  "/Users/honza/projects/calc/MainFrame.cpp" -g -O0 -Wall   -o ./Debug/MainFrame.cpp.o -I/usr/local/bin  -I. -I.
/usr/bin/g++   -c  "/Users/honza/projects/calc/wxcrafter.cpp" -g -O0 -Wall   -o ./Debug/wxcrafter.cpp.o -I/usr/local/bin  -I. -I.
/usr/bin/g++   -c  "/Users/honza/projects/calc/wxcrafter_bitmaps.cpp" -g -O0 -Wall   -o ./Debug/wxcrafter_bitmaps.cpp.o -I/usr/local/bin  -I. -I.
/Users/honza/projects/calc/main.cpp:1:10: fatal error: 'wx/app.h' file not found
#include <wx/app.h>
         ^
1 error generated.
make[1]: *** [Debug/main.cpp.o] Error 1
make[1]: *** Waiting for unfinished jobs....
In file included from In file included from /Users/honza/projects/calc/wxcrafter.cpp/Users/honza/projects/calc/MainFrame.cpp::71:
:
In file included from ./MainFrame.h./wxcrafter.h::310:
:10:./wxcrafter.h :fatal error10: :10'wx/settings.h' file not found:
 fatal error: 'wx/settings.h' file not found
#include <wx/settings.h>
         ^
#include <wx/settings.h>
         ^
/Users/honza/projects/calc/wxcrafter_bitmaps.cpp:5:10: fatal error: 'wx/wxprec.h' file not found
#include <wx/wxprec.h>
         ^
1 error generated.
1 error generated.
1 error generated.
make[1]: *** [Debug/wxcrafter.cpp.o] Error 1
make[1]: *** [Debug/MainFrame.cpp.o] Error 1
make[1]: *** [Debug/wxcrafter_bitmaps.cpp.o] Error 1
make: *** [All] Error 2
4 errors, 0 warnings
```

**Comment by pauljohnleonard** [comment]
Same as HonzaMac.

**Comment by eranif** [comment]
It looks like that when lauching CodeLite the environment variables are not passed correctly to CodeLite (i.e. PATH is not set properly)
What is the output of `which wx-config` from the command line?
What happens when you change `wx-config` to its full path in the project settings?
`Project settings->common settings->general->compiler->c++ compiler options`
and 
`Project settings->common settings->general->linker->linker options`

**Comment by pauljohnleonard** [comment]
`/usr/Local/bin/wx-config`

Your advice fixes it.  Thanks.
