### ISSUE TITLE
[Bug]: Linux build from master is broken since commit d882e5a8c7cea691bfb72c32478b4a9a8071e77a

### ISSUE THREAD

**Issue by UffeJakobsen** [eranif/codelite#3542]
### What happened?

Linux build from master is broken since commit d882e5a8c7cea691bfb72c32478b4a9a8071e77a

```
/tmp/codelite.git/Plugin/ThemeImporters/ThemeImporterErrorlist.cpp: In member function ‘virtual LexerConf::Ptr_t ThemeImporterErrorlist::Import(const wxFileName&)’:
/tmp/codelite.git/Plugin/ThemeImporters/ThemeImporterErrorlist.cpp:44:24: error: ‘wxSTC_ERR_GCC_EXCERPT’ was not declared in this scope
   44 |     AddProperty(lexer, wxSTC_ERR_GCC_EXCERPT, "GCC code excerpt and pointer to issue", Cyan(is_dark),
      |                        ^~~~~~~~~~~~~~~~~~~~~
/tmp/codelite.git/Plugin/ThemeImporters/ThemeImporterErrorlist.cpp:46:24: error: ‘wxSTC_ERR_BASH’ was not declared in this scope; did you mean ‘wxSTC_ERR_ABSF’?
   46 |     AddProperty(lexer, wxSTC_ERR_BASH, "Bash diagnostic line", Red(is_dark), m_editor.bg_colour);
      |                        ^~~~~~~~~~~~~~
      |                        wxSTC_ERR_ABSF
```

### Version

Self compiled

### Operating system

Linux

**Comment by eranif** [comment]
This was fixed earlier  - try now

**Comment by eranif** [comment]
This commit should have fix this
https://github.com/eranif/codelite/commit/e6f8fd88406e64ff64b8730b0fd3f9422e5a0dc5

**Comment by UffeJakobsen** [comment]
Thanks :+1:  :-)
