### ISSUE TITLE
MariaDB 10.3 breaks build when using WITH_MYSQL=1

### ISSUE THREAD

**Issue by hpmachining** [eranif/codelite#2215]
In Arch Linux and Debian unstable, Codelite won't build using WITH_MYSQL=1 with MariaDB 10.3. Here is how I configured:
```
cmake -G "Unix Makefiles" \
-DCMAKE_BUILD_TYPE=Release \
-DENABLE_CLANG=1 \
-DENABLE_LLDB=1 \
-DWITH_MYSQL=1 \
-DCMAKE_INSTALL_LIBDIR=lib ..
```
Here is the error:
```
/home/paul/projects/codelite/sdk/databaselayer/src/dblayer/MysqlPreparedStatementWrapper.cpp: In member function ‘int MysqlPreparedStatementWrapper::RunQuery()’:
/home/paul/projects/codelite/sdk/databaselayer/src/dblayer/MysqlPreparedStatementWrapper.cpp:97:25: error: ‘MYSQL_STMT’ {aka ‘struct st_mysql_stmt’} has no member named ‘affected_rows’; did you mean ‘prefetch_rows’?
   return (m_pStatement->affected_rows);
                         ^~~~~~~~~~~~~
                         prefetch_rows
```
This is what I have discovered. MariaDB now has 2 `mysql.h` files, one in `/usr/include/mariadb` and one in `/usr/include/mariadb/server`. If I change `#include "mysql.h"` to `#include "server/mysql.h"` in the file mentioned in the error, the build succeeds. There are 7 other files under `databaselayer` that have the same `include`, but they don't cause the build to fail. If I change all of them to `server/mysql.h` the build still succeeds. 

I don't know enough about the code to know if this is an appropriate workaround or not. The only reason I found it is because the PKGBUILD file in the Arch Linux AUR defaults to building with mysql support. Since I don't actually use the mysql features, I don't know how to test if everything works like it should. Anyways, I just wanted to make you aware of the situation.

**Comment by dghart** [comment]
Thank you for reporting this, and even more for identifying the cause.

It should be fixed in git by 615aa07b2 and the diff of that commit should apply to CodeLite 12.0 too.

**Comment by hpmachining** [comment]
@dghart You're welcome. Debian build works but not Arch. I gave you incomplete information. I didn't catch it before, but Arch uses `mysql` sub-directory instead of `mariadb`. Adding `mysql/server` to the `PATH_SUFFIXES` list in the [CMakeList.txt](https://github.com/eranif/codelite/commit/615aa07b24fa4703a03f5c1e6860351732e24ec6#diff-65a75be0af5b5b1531d6434acc69809e) works for me on both systems.

**Comment by dghart** [comment]
Thanks again. Added in 09d0165. Please let me know if there's still a problem.
