### ISSUE TITLE
wxString::starts_with() is not present in wxWidgets 3.0.x

### ISSUE THREAD

**Issue by uffejakobsen** [eranif/codelite#2689]
wxString starts_with() is not present in wxWidgets 3.0.x

functionality introduced in commit 956c4c2a453a71d21c9fb4450ba169603d485cc0 cannot compile on wxWidgets 3.0.x due to use of wxString::starts_with()

```
commit 956c4c2a453a71d21c9fb4450ba169603d485cc0
Author:     Eran Ifrah <eran.ifrah@gmail.com>
AuthorDate: Sat Mar 13 00:50:57 2021 +0200
Commit:     Eran Ifrah <eran.ifrah@gmail.com>
CommitDate: Sat Mar 13 00:50:57 2021 +0200

    Use the file system workspace settings dialog for the Remote workspace

```

```
/tmp/CodeLite/fileutils.cpp: In static member function ‘static bool FileUtils::ParseURI(const wxString&, wxString&, wxString&, wxString&, wxString&, wxString&)’:
/tmp/CodeLite/fileutils.cpp:792:12: error: ‘const class wxString’ has no member named ‘starts_with’; did you mean ‘StartsWith’?
  792 |     if(uri.starts_with("file://")) {
      |            ^~~~~~~~~~~
      |            StartsWith
/tmp/CodeLite/fileutils.cpp:796:19: error: ‘const class wxString’ has no member named ‘starts_with’; did you mean ‘StartsWith’?
  796 |     } else if(uri.starts_with("ssh://")) {
      |                   ^~~~~~~~~~~
      |                   StartsWith
/tmp/CodeLite/fileutils.cpp:824:1: warning: control reaches end of non-void function [-Wreturn-type]
  824 | }
      | ^
```

wxString::starts_with() seems to have been introduced after wxWidgets 3.0x

https://docs.wxwidgets.org/trunk/classwx_string.html#ac1f4a296f7de09d4dfff8abb0fabf46c
https://docs.wxwidgets.org/3.0/classwx_string.html#a627b084ee8088734e1b28ee23d67f7bb
